// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azuwehjpqqmhfzfluiui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6dXdlaGpwcXFtaGZ6Zmx1aXVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMjI4NzMsImV4cCI6MjA2NDg5ODg3M30.EPZlbEtEBcfZUhaBgwVJbjs6FCP5tJVyUjqj1eHdDaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);